/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'sender' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface IrrigationRecommendation {
  'soilMoisture' : number,
  'temperature' : number,
  'timestamp' : bigint,
  'recommendation' : string,
  'reason' : string,
}
export interface PlantHealthAnalysis {
  'healthStatus' : string,
  'timestamp' : bigint,
  'greenRatio' : number,
  'image' : Uint8Array,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface WeatherData {
  'temperature' : number,
  'humidity' : number,
  'timestamp' : bigint,
  'conditions' : string,
}
export interface _SERVICE {
  '__chatHistory' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, ChatMessage]>
  >,
  '__irrigationRecommendations' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, IrrigationRecommendation]>
  >,
  '__plantAnalyses' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, PlantHealthAnalysis]>
  >,
  '__weatherDataStore' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<[bigint, WeatherData]>
  >,
  'addChatMessage' : ActorMethod<[string, string], undefined>,
  'addIrrigationRecommendation' : ActorMethod<
    [number, number, string, string],
    undefined
  >,
  'analyzePlantHealth' : ActorMethod<[Uint8Array, number], undefined>,
  'fetchWeatherData' : ActorMethod<[string], string>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getChatHistoryForExport' : ActorMethod<[], Array<ChatMessage>>,
  'getIrrigationRecommendations' : ActorMethod<
    [],
    Array<IrrigationRecommendation>
  >,
  'getIrrigationRecommendationsForExport' : ActorMethod<
    [],
    Array<IrrigationRecommendation>
  >,
  'getLatestWeatherData' : ActorMethod<[], [] | [WeatherData]>,
  'getPlantAnalyses' : ActorMethod<[], Array<PlantHealthAnalysis>>,
  'getPlantAnalysesForExport' : ActorMethod<[], Array<PlantHealthAnalysis>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateWeatherData' : ActorMethod<[number, number, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];