/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatMessage = IDL.Record({
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const IrrigationRecommendation = IDL.Record({
  'soilMoisture' : IDL.Float64,
  'temperature' : IDL.Float64,
  'timestamp' : IDL.Int,
  'recommendation' : IDL.Text,
  'reason' : IDL.Text,
});
export const PlantHealthAnalysis = IDL.Record({
  'healthStatus' : IDL.Text,
  'timestamp' : IDL.Int,
  'greenRatio' : IDL.Float64,
  'image' : IDL.Vec(IDL.Nat8),
});
export const WeatherData = IDL.Record({
  'temperature' : IDL.Float64,
  'humidity' : IDL.Float64,
  'timestamp' : IDL.Int,
  'conditions' : IDL.Text,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '__chatHistory' : IDL.Func(
      [IDL.Opt(IDL.Int), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Int, ChatMessage))],
      ['query'],
    ),
  '__irrigationRecommendations' : IDL.Func(
      [IDL.Opt(IDL.Int), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Int, IrrigationRecommendation))],
      ['query'],
    ),
  '__plantAnalyses' : IDL.Func(
      [IDL.Opt(IDL.Int), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Int, PlantHealthAnalysis))],
      ['query'],
    ),
  '__weatherDataStore' : IDL.Func(
      [IDL.Opt(IDL.Int), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Int, WeatherData))],
      ['query'],
    ),
  'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addIrrigationRecommendation' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'analyzePlantHealth' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Float64], [], []),
  'fetchWeatherData' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getChatHistoryForExport' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getIrrigationRecommendations' : IDL.Func(
      [],
      [IDL.Vec(IrrigationRecommendation)],
      ['query'],
    ),
  'getIrrigationRecommendationsForExport' : IDL.Func(
      [],
      [IDL.Vec(IrrigationRecommendation)],
      ['query'],
    ),
  'getLatestWeatherData' : IDL.Func([], [IDL.Opt(WeatherData)], ['query']),
  'getPlantAnalyses' : IDL.Func([], [IDL.Vec(PlantHealthAnalysis)], ['query']),
  'getPlantAnalysesForExport' : IDL.Func(
      [],
      [IDL.Vec(PlantHealthAnalysis)],
      ['query'],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateWeatherData' : IDL.Func([IDL.Float64, IDL.Float64, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatMessage = IDL.Record({
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const IrrigationRecommendation = IDL.Record({
    'soilMoisture' : IDL.Float64,
    'temperature' : IDL.Float64,
    'timestamp' : IDL.Int,
    'recommendation' : IDL.Text,
    'reason' : IDL.Text,
  });
  const PlantHealthAnalysis = IDL.Record({
    'healthStatus' : IDL.Text,
    'timestamp' : IDL.Int,
    'greenRatio' : IDL.Float64,
    'image' : IDL.Vec(IDL.Nat8),
  });
  const WeatherData = IDL.Record({
    'temperature' : IDL.Float64,
    'humidity' : IDL.Float64,
    'timestamp' : IDL.Int,
    'conditions' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '__chatHistory' : IDL.Func(
        [IDL.Opt(IDL.Int), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Int, ChatMessage))],
        ['query'],
      ),
    '__irrigationRecommendations' : IDL.Func(
        [IDL.Opt(IDL.Int), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Int, IrrigationRecommendation))],
        ['query'],
      ),
    '__plantAnalyses' : IDL.Func(
        [IDL.Opt(IDL.Int), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Int, PlantHealthAnalysis))],
        ['query'],
      ),
    '__weatherDataStore' : IDL.Func(
        [IDL.Opt(IDL.Int), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Int, WeatherData))],
        ['query'],
      ),
    'addChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addIrrigationRecommendation' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'analyzePlantHealth' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Float64], [], []),
    'fetchWeatherData' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getChatHistoryForExport' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getIrrigationRecommendations' : IDL.Func(
        [],
        [IDL.Vec(IrrigationRecommendation)],
        ['query'],
      ),
    'getIrrigationRecommendationsForExport' : IDL.Func(
        [],
        [IDL.Vec(IrrigationRecommendation)],
        ['query'],
      ),
    'getLatestWeatherData' : IDL.Func([], [IDL.Opt(WeatherData)], ['query']),
    'getPlantAnalyses' : IDL.Func(
        [],
        [IDL.Vec(PlantHealthAnalysis)],
        ['query'],
      ),
    'getPlantAnalysesForExport' : IDL.Func(
        [],
        [IDL.Vec(PlantHealthAnalysis)],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateWeatherData' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };