/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface IrrigationRecommendation {
    soilMoisture: number;
    temperature: number;
    timestamp: bigint;
    recommendation: string;
    reason: string;
}
export interface WeatherData {
    temperature: number;
    humidity: number;
    timestamp: bigint;
    conditions: string;
}
export interface ChatMessage {
    sender: string;
    message: string;
    timestamp: bigint;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface PlantHealthAnalysis {
    healthStatus: string;
    timestamp: bigint;
    greenRatio: number;
    image: Uint8Array;
}
export interface backendInterface {
    __chatHistory(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, ChatMessage]>>;
    __irrigationRecommendations(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, IrrigationRecommendation]>>;
    __plantAnalyses(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, PlantHealthAnalysis]>>;
    __weatherDataStore(ko: bigint | null, count: bigint | null): Promise<Array<[bigint, WeatherData]>>;
    addChatMessage(sender: string, message: string): Promise<void>;
    addIrrigationRecommendation(soilMoisture: number, temperature: number, recommendation: string, reason: string): Promise<void>;
    analyzePlantHealth(image: Uint8Array, greenRatio: number): Promise<void>;
    fetchWeatherData(apiUrl: string): Promise<string>;
    getChatHistory(): Promise<Array<ChatMessage>>;
    getChatHistoryForExport(): Promise<Array<ChatMessage>>;
    getIrrigationRecommendations(): Promise<Array<IrrigationRecommendation>>;
    getIrrigationRecommendationsForExport(): Promise<Array<IrrigationRecommendation>>;
    getLatestWeatherData(): Promise<WeatherData | null>;
    getPlantAnalyses(): Promise<Array<PlantHealthAnalysis>>;
    getPlantAnalysesForExport(): Promise<Array<PlantHealthAnalysis>>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateWeatherData(temperature: number, humidity: number, conditions: string): Promise<void>;
}
import type { WeatherData as _WeatherData } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __chatHistory(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, ChatMessage]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__chatHistory(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__chatHistory(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __irrigationRecommendations(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, IrrigationRecommendation]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__irrigationRecommendations(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__irrigationRecommendations(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __plantAnalyses(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, PlantHealthAnalysis]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__plantAnalyses(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__plantAnalyses(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __weatherDataStore(arg0: bigint | null, arg1: bigint | null): Promise<Array<[bigint, WeatherData]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__weatherDataStore(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__weatherDataStore(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addChatMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addChatMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChatMessage(arg0, arg1);
            return result;
        }
    }
    async addIrrigationRecommendation(arg0: number, arg1: number, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIrrigationRecommendation(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIrrigationRecommendation(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async analyzePlantHealth(arg0: Uint8Array, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzePlantHealth(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzePlantHealth(arg0, arg1);
            return result;
        }
    }
    async fetchWeatherData(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchWeatherData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchWeatherData(arg0);
            return result;
        }
    }
    async getChatHistory(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory();
            return result;
        }
    }
    async getChatHistoryForExport(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistoryForExport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistoryForExport();
            return result;
        }
    }
    async getIrrigationRecommendations(): Promise<Array<IrrigationRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIrrigationRecommendations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIrrigationRecommendations();
            return result;
        }
    }
    async getIrrigationRecommendationsForExport(): Promise<Array<IrrigationRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIrrigationRecommendationsForExport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIrrigationRecommendationsForExport();
            return result;
        }
    }
    async getLatestWeatherData(): Promise<WeatherData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestWeatherData();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestWeatherData();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlantAnalyses(): Promise<Array<PlantHealthAnalysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlantAnalyses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlantAnalyses();
            return result;
        }
    }
    async getPlantAnalysesForExport(): Promise<Array<PlantHealthAnalysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlantAnalysesForExport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlantAnalysesForExport();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateWeatherData(arg0: number, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWeatherData(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWeatherData(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WeatherData]): WeatherData | null {
    return value.length === 0 ? null : value[0];
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
